name: rust
on:
  push: null
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: run tests
      run: cargo test
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Run cargo fmt
      run: cargo fmt --all -- --check
      id: _bre_fmt
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo -V && rustc -V
    - name: Run clippy
      run: cargo clippy --all --tests --all-features --all-targets -- -D warnings
    - uses: dtolnay/rust-toolchain@stable
      if: '!cancelled() && steps._bre_fmt.conclusion == ''success'''
    - name: muddy
      run: 'cargo rustdoc -p muddy --all-features -- -D warnings

        '
      if: '!cancelled() && steps._bre_fmt.conclusion == ''success'''
