name: rust
on:
  push: null
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - name: stepify-probe-fmt
      run: echo stepify-probe-fmt
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Run cargo fmt
      run: cargo fmt --all -- --check
    - name: stepify-tail-fmt
      run: echo stepify-tail-fmt
  clippy:
    name: Clippy
    needs:
    - fmt
    runs-on: ubuntu-latest
    steps:
    - name: stepify-probe-clippy
      run: echo stepify-probe-clippy
    - name: stepify-fault-clippy
      run: exit 1
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo -V && rustc -V
    - name: Run clippy
      run: cargo clippy --all --tests --all-features --all-targets -- -D warnings
    - name: stepify-tail-clippy
      run: echo stepify-tail-clippy
  rustdoc:
    name: Rustdoc
    needs:
    - fmt
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: stepify-probe-rustdoc
      run: echo stepify-probe-rustdoc
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: muddy
      run: 'cargo rustdoc -p muddy --all-features -- -D warnings

        '
    - name: stepify-tail-rustdoc
      run: echo stepify-tail-rustdoc
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: run tests
      run: cargo test
